### ISSUE TITLE
3월 23일 [실버 2] DFS와 BFS

### ISSUE THREAD

**Issue by jinbekim** [AlgoAlgo42/AlgoAlgo#148]
**문제 링크** :
https://www.acmicpc.net/problem/1260
**문제 설명** :
dfs와 bfs
**풀이 방법 or TAG** :

**예정 풀이 시간** :

**Comment by bs7703** [comment]
제가 자바스크립트의 자료구조형의 대입을 잘몰라서그런데, 일단 하나 생각해볼만한건 "양방향 간선" 인데 데이터를 첨삭하실떄 각노드에 양방향성으로 추가해주신게맞는지? 확인해봐야할거같습니다. 3-4로가는간선같은경우는 노드3과 노드4에 모두정보를 넣고 탐색을 하신건가요?
